## Упражнения по библиотеке Numpy

In [1]:
import numpy as np

**1.** Дан случайный массив, поменять знак у элементов, значения которых между 3 и 8

In [5]:
rand_array = np.random.randint(0, 10, 20)
print(rand_array)
rand_array[(rand_array > 3) & (rand_array < 8)] *= -1
print(rand_array) 

[2 0 2 9 5 1 9 7 4 9 7 7 0 2 2 2 5 8 0 6]
[ 2  0  2  9 -5  1  9 -7 -4  9 -7 -7  0  2  2  2 -5  8  0 -6]


**2.** Заменить максимальный элемент случайного массива на 0

In [9]:
rand_array = np.random.randint(0, 10, 20)
print(rand_array)
print(max(rand_array))
max_index = np.argmax(rand_array)
rand_array[max_index] = 0
print(rand_array)


[5 4 4 4 6 0 7 9 7 0 4 4 6 0 9 3 4 1 2 0]
9
[5 4 4 4 6 0 7 0 7 0 4 4 6 0 9 3 4 1 2 0]


Построить прямое произведение массивов (все комбинации с каждым элементом). На вход подается двумерный массив**3.** 

In [26]:
rand_array2d = np.random.randint(0, 10, (2,2))
print(rand_array)
array_a, array_b = np.meshgrid(rand_array2d[:, 0], rand_array2d[:, 1])
print(f'array_a: {array_a}')
print(f'array_b: {array_b}')
result = np.array(np.vstack([array_a.ravel(), array_b.ravel()])).T
print(f'result: {result}')

[[3 8]
 [2 0]]
array_a: [[8 7]
 [8 7]]
array_b: [[8 8]
 [6 6]]
result: [[8 8]
 [7 8]
 [8 6]
 [7 6]]


**4.** Даны 2 массива A (8x3) и B (2x2). Найти строки в A, которые содержат элементы из каждой строки в B, независимо от порядка элементов в B

In [31]:
array_a83 = np.random.randint(0, 10, (8,3))
array_b22 = np.random.randint(0, 10, (2,2))
print(array_a83)
print(array_b22)
match_rows = []
for b_row in array_b22:
	for i,a_row in enumerate(array_a83):
		if np.all(np.isin(b_row, a_row)):
			match_rows.append(i)
match_rows = list(set(match_rows))
print('---- match_rows------')
print(match_rows)

[[9 1 3]
 [0 9 0]
 [0 0 0]
 [7 4 1]
 [2 2 9]
 [2 4 7]
 [8 4 9]
 [2 8 2]]
[[9 6]
 [0 9]]
---- match_rows------
[1]


**5.** Дана 10x3 матрица, найти строки из неравных значений (например строка [2,2,3] остается, строка [3,3,3] удаляется)

In [44]:
array_103 = np.array([[1,0,1],[1,1,1], [1,1,1],[0,0,0],[1,0,1],[1,0,1],[1,1,1],[1,0,1],[0,0,1],[1,0,1]])
print(array_103)
unique_rows = array_103[np.array([len(set(row)) > 1 for row in array_103])]  
print(unique_rows)

[[1 0 1]
 [1 1 1]
 [1 1 1]
 [0 0 0]
 [1 0 1]
 [1 0 1]
 [1 1 1]
 [1 0 1]
 [0 0 1]
 [1 0 1]]
[[1 0 1]
 [1 0 1]
 [1 0 1]
 [1 0 1]
 [0 0 1]
 [1 0 1]]


**6.** Дан двумерный массив. Удалить те строки, которые повторяются

In [45]:
array_2d = np.array([[1,0,1],[1,1,1],[1,0,1]])
print(array_2d)
unique_rows = np.unique(array_2d, axis=0)
print(unique_rows)

[[1 0 1]
 [1 1 1]
 [1 0 1]]
[[1 0 1]
 [1 1 1]]


______
______

Для каждой из следующих задач (1-5) нужно привести 2 реализации – одна без использования numpy (cчитайте, что там, где на входе или выходе должны быть numpy array, будут просто списки), а вторая полностью векторизованная с использованием numpy (без использования питоновских циклов/map/list comprehension).


__Замечание 1.__ Можно считать, что все указанные объекты непустые (к примеру, в __задаче 1__ на диагонали матрицы есть ненулевые элементы).

__Замечание 2.__ Для большинства задач решение занимает не больше 1-2 строк.

___

* __Задача 1__: Подсчитать произведение ненулевых элементов на диагонали прямоугольной матрицы.  
 Например, для X = np.array([[1, 0, 1], [2, 0, 2], [3, 0, 3], [4, 4, 4]]) ответ 3.

In [56]:
#Numpy
arrayNumPy_2d = np.array([[1, 0, 1], [2, 0, 2], [3, 0, 3], [4, 4, 4]])
array_diagonal = np.diagonal(arrayNumPy_2d)
print(f'Numpy: {array_diagonal}')
print(np.prod(array_diagonal[array_diagonal != 0]))

# without Numpy
result = 1 # as diagonal have non0 elements
array_2d = [[1, 0, 1], [2, 0, 2], [3, 0, 3], [4, 4, 4]]
for i in range(min(len(array_2d[0]), len(array_2d))):
	if array_2d[i][i] != 0:
		result *= array_2d[i][i]
print('---Without Numpy----')
print(result)
	



Numpy: [1 0 3]
3
---Without Numpy----
3


* __Задача 2__: Даны два вектора x и y. Проверить, задают ли они одно и то же мультимножество.  
  Например, для x = np.array([1, 2, 2, 4]), y = np.array([4, 2, 1, 2]) ответ True.

In [61]:
# Numpy
x = np.array([1, 2, 2, 4])  
y = np.array([4, 2, 1, 2]) 
unique_x, frequency_x = np.unique(x, return_counts=True)
unique_y, frequency_y = np.unique(y, return_counts=True)  
check_multiset_np = np.array_equal(unique_x, unique_y) & np.array_equal(frequency_x, frequency_y)
print(check_multiset_np)

# without Numpy
from collections import Counter 
x = [1, 2, 2, 4]  
y = [4, 2, 1, 2] 
check_multiset = Counter(x) == Counter(y)
print(check_multiset)



True
True


* __Задача 3__: Найти максимальный элемент в векторе x среди элементов, перед которыми стоит ноль. 
 Например, для x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0]) ответ 5.

In [65]:
# Numpy
x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0])
elem_after_0 = x[np.where(x[:-1] == 0)[0] + 1]
max_after_0np = max(elem_after_0)
print(max_after_0np)

# without Numpy
x = [6, 2, 0, 3, 0, 0, 5, 7, 0] 
max_after_0 = None
for i in range(1, len(x)):
	if x[i-1] == 0:
		if max_after_0 is None or x[i] > max_after_0:
			max_after_0 = x[i]
print(max_after_0)

5
5


* __Задача 4__: Реализовать кодирование длин серий (Run-length encoding). Для некоторого вектора x необходимо вернуть кортеж из двух векторов одинаковой длины. Первый содержит числа, а второй - сколько раз их нужно повторить.  
 Например, для x = np.array([2, 2, 2, 3, 3, 3, 5]) ответ (np.array([2, 3, 5]), np.array([3, 3, 1])).

In [71]:
# Numpy
array_1np = np.array([2, 2, 2, 3, 3, 3, 5])
def get_uniq_freq_tuple_np(x):
	unique_elements, frequency = np.unique(x, return_counts=True)
	return (unique_elements, frequency)
uniq_freq_tuple_np = get_uniq_freq_tuple_np(array_1np)
print(uniq_freq_tuple_np)

# without Numpy
array_1 = [2, 2, 2, 3, 3, 3, 5]
def get_uniq_freq_tuple(x):  
    values, frequencies = [], []  
    current_value, current_count = x[0], 1  
    for i in range(1, len(x)):  
        if x[i] == current_value:  
            current_count += 1  
        else:  
            values.append(current_value)  
            frequencies.append(current_count)  
            current_value, current_count = x[i], 1   
    values.append(current_value)  
    frequencies.append(current_count)  
    return (values, frequencies)

uniq_freq_tuple = get_uniq_freq_tuple(array_1)
print(uniq_freq_tuple)

(array([2, 3, 5]), array([3, 3, 1]))
([2, 3, 5], [3, 3, 1])


* __Задача 5__: Даны две выборки объектов - X и Y. Вычислить матрицу евклидовых расстояний между объектами. Сравните с функцией scipy.spatial.distance.cdist по скорости работы.

In [79]:
import time
from scipy.spatial.distance import cdist

# Numpy
np.random.seed(0)  
a = np.random.rand(1000, 10)   
b = np.random.rand(1000, 10)  

def evclid_distance_numpy(x, y):  
    dists = np.sqrt(((x[:, np.newaxis] - y[np.newaxis, :]) ** 2).sum(axis=2))  
    return dists  

start_time = time.time()  
distances_numpy = evclid_distance_numpy(a, b)  
numpy_time = time.time() - start_time
print(f'Numpy numpy_time: {numpy_time}')

# scipy.spatial.distance.cdist
start_time = time.time()  
distances_cdist = cdist(a, b, metric='euclidean')  
cdist_time = time.time() - start_time
print(f'scipy cdist_time: {cdist_time}')

 

Numpy numpy_time: 0.18793010711669922
scipy cdist_time: 0.03909611701965332


_______
________

* #### __Задача 6__: CrunchieMunchies __*__

Вы работаете в отделе маркетинга пищевой компании MyCrunch, которая разрабатывает новый вид вкусных, полезных злаков под названием **CrunchieMunchies**.

Вы хотите продемонстрировать потребителям, насколько полезны ваши хлопья по сравнению с другими ведущими брендами, поэтому вы собрали данные о питании нескольких разных конкурентов.

Ваша задача - использовать вычисления Numpy для анализа этих данных и доказать, что ваши **СrunchieMunchies** - самый здоровый выбор для потребителей.


In [77]:
import numpy as np

1. Просмотрите файл cereal.csv. Этот файл содержит количества калорий для различных марок хлопьев. Загрузите данные из файла и сохраните их как calorie_stats.

In [81]:
calorie_stats = np.loadtxt("./data/cereal.csv", delimiter=",")
calorie_stats

array([ 70., 120.,  70.,  50., 110., 110., 110., 130.,  90.,  90., 120.,
       110., 120., 110., 110., 110., 100., 110., 110., 110., 100., 110.,
       100., 100., 110., 110., 100., 120., 120., 110., 100., 110., 100.,
       110., 120., 120., 110., 110., 110., 140., 110., 100., 110., 100.,
       150., 150., 160., 100., 120., 140.,  90., 130., 120., 100.,  50.,
        50., 100., 100., 120., 100.,  90., 110., 110.,  80.,  90.,  90.,
       110., 110.,  90., 110., 140., 100., 110., 110., 100., 100., 110.])

2. В одной порции CrunchieMunchies содержится 60 калорий. Насколько выше среднее количество калорий у ваших конкурентов?

Сохраните ответ в переменной average_calories и распечатайте переменную в терминале

In [88]:
crunchiemunchies_colories = 60
average_calories_competitors = np.mean(calorie_stats)
print(f'average_calories_competitors: {average_calories_competitors}' )
average_calories =  average_calories_competitors - crunchiemunchies_colories
print(f'average_calories diff: {average_calories}')

average_calories_competitors: 106.88311688311688
average_calories diff: 46.883116883116884


3. Корректно ли среднее количество калорий отражает распределение набора данных? Давайте отсортируем данные и посмотрим.

Отсортируйте данные и сохраните результат в переменной calorie_stats_sorted. Распечатайте отсортированную информацию

In [85]:
calorie_stats_sorted = np.sort(calorie_stats)
print(calorie_stats_sorted)

[ 50.  50.  50.  70.  70.  80.  90.  90.  90.  90.  90.  90.  90. 100.
 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100.
 100. 100. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110.
 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110.
 110. 110. 110. 120. 120. 120. 120. 120. 120. 120. 120. 120. 120. 130.
 130. 140. 140. 140. 150. 150. 160.]


4. Похоже, что большинство значений выше среднего. Давайте посмотрим, является ли медиана наиболее корректным показателем набора данных.

Вычислите медиану набора данных и сохраните свой ответ в median_calories. Выведите медиану, чтобы вы могли видеть, как она сравнивается со средним значением.

In [86]:
median_calories = np.median(calorie_stats)
print(median_calories)

110.0


5. В то время как медиана показывает, что по крайней мере половина наших значений составляет более 100 калорий, было бы более впечатляюще показать, что значительная часть конкурентов имеет более высокое количество калорий, чем CrunchieMunchies.

Рассчитайте различные процентили и распечатайте их, пока не найдете наименьший процентиль, превышающий 60 калорий. Сохраните это значение в переменной nth_percentile.

In [93]:
percentile = 0
min_percentile = None
while True:
	current_percentile = np.percentile(calorie_stats, percentile)
	if current_percentile > crunchiemunchies_colories:
		min_percentile = current_percentile
		break
	percentile += 1

print(f'min_percentile: {min_percentile}')

min_percentile: 70.0


6. Хотя процентиль показывает нам, что у большинства конкурентов количество калорий намного выше, это неудобная концепция для использования в маркетинговых материалах.

Вместо этого давайте подсчитаем процент хлопьев, в которых содержится более 60 калорий на порцию. Сохраните свой ответ в переменной more_calories и распечатайте его

In [94]:
count_above_60 = np.sum(calorie_stats > crunchiemunchies_colories)
total_count = calorie_stats.size
more_calories = count_above_60 / total_count *100
print(f'more_calories : {more_calories}')

more_calories : 96.1038961038961


7. Это действительно высокий процент. Это будет очень полезно, когда мы будем продвигать CrunchieMunchies. Но один вопрос заключается в том, насколько велики различия в наборе данных? Можем ли мы сделать обобщение, что в большинстве злаков содержится около 100 калорий или разброс еще больше?

Рассчитайте величину отклонения, найдя стандартное отклонение, Сохраните свой ответ в calorie_std и распечатайте на терминале. Как мы можем включить эту ценность в наш анализ?

In [98]:
calorie_std = np.std(calorie_stats)
print(calorie_std)

19.35718533390827


Напишите короткий абзац, в котором кратко изложите свои выводы и то, как, по вашему мнению, эти данные могут быть использованы в интересах Mycrunch при маркетинге CrunchieMunchies.8. 

In [167]:
После проведенного анализа данных о калориях конкурентов можно сделать выводч что:
- среднее значение калорийности по кокурентам: 106.9 - наше: 60. Разница 46.9
- колорийность наших хлопьев в 96% ниже чем у конкурентов
- среднее значение калорий по конкурентам превышает 100  
- медиана (110.0) указывает на то, что как минимум у половины конкуретнтов колорийность хлопьев более 110
- min_percentile: 70.0 показывает, что значительная часть конкурентов имеет больше калорий, чем CrunchieMunchies (60)
- рассматривая длинный хвост продуктов, большинство конкурентов предлагает хлопья с калорийностью от 100 до 160 калорий, что видно из стандартного отклонения.